apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: agroflow
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123
  POSTGRES_INITDB_ARGS: "--auth-host=md5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: agroflow
data:
  init-databases.sql: |
    CREATE DATABASE agroflow_central;
    CREATE DATABASE agroflow_inventario;
    CREATE DATABASE agroflow_facturacion;
    
    GRANT ALL PRIVILEGES ON DATABASE agroflow_central TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE agroflow_inventario TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE agroflow_facturacion TO postgres;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: agroflow
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data
        emptyDir: {}
      - name: postgres-init-scripts
        configMap:
          name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: agroflow
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP